sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

after_success:
  - mvn jacoco:report coveralls:report

env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "gjGujK7IPO2oEUzMfs9lV67K2Nxv0aQ9/MZyvZ8OJXq8bw0BDKj2cBZFy8ENqHte5E53RctjN9C81JvBfZl9PLjQwX7UBVh7N8ZM5JvcchYcfBEbDh/QFhv7bXNr2vM7rqq71uOM+z/SYj91GwKg0zDcnT8Ggpon/Voozk3Jm+bAkDuCv+8wa2pNZPOnshJTAeEdMAcwppC9F+Aye8mGlq/qBsScUrrH1ducYbzlbDoVlPKZd/GlkzMKV5zSwYyrJ/jSRK7r2lDZnOV9i/1woESodGkTCJoaqyj5OaCpAp7qizKCOcsz8/jr2hCPaJ7U2tbSoRI7nugfnRpyUXts9qbCnEwrBphMaa2kLSfl5fqW7798ihTzGS57Pi9L/nELCpsy61Ty72F8j6ZgTep5nDLnC4GLRF7P06jfXkaGM5MtpTy0sTYC0lBpaCbEHVU3sNYwDM5Gj/ue0GAh9NHYpD3e5sDOt+Cn6YJsHJY4Gv5sGGPzNc4DPwgQQUVgXEYk316h9ga9GouJUUqS0GLI+qOJio9AmNWa/qWBo39R9Rsm8CRpTnBmA6bvas/QVRg9UG2eizCud2arZjCVPyKKirUhPBZTuKRTMNmEw6eIFjlnFPzbj+KoOjtmOuIcKFut6yrjOMfreMQLN3RDKDLQkWMVlOlad/Skl1W7FBChwfM="
    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
    - secure: "Z9iURpi/sOh/x2ezZKOtvgGnd4kHveROAzUYY+y8q76ukKq3RlC+bdJC0a3fGjdg85qm4fDrDaY8WAWBSmeK7+9qrqTJJKPQCT2zOO0bnKKH79Ik6raMKsC+tKl0i3PGke7fhTk4nJuQFeyJt4it32DBgT95wN6VCXUoG7SA9i6aFZyEvaCxrWHDHsfD6rNUy25CBjQQSABOp868BLuyz7JF2j05A/618UqFJj4ehHPTSnDhoEFGotWFuMRiyrCgu/wvL6UQGkqKGaxGmdik4QO/MPiywSPHdPGjzoH0Oorkouu0NAtw0I0T7Q8i93/I1QBLQwy2mY/nhjXwIX+uQe3MYRJCEkwLz1g6Dim4SHkD9exS5ZZBew/g+IRymKfrbNL5Ieu+VFQw9zSdflUJQSJltz4nWkQr8PEQHy1gXQ2mwBXzRxWfWNzKpQXPTm9tXB+CyVYRs0Ldk5FoLV+P13i61NDp8eOOnAmfikEcRv3p1GVQh2Mzo0gjhxFl3/74bxsJLHobZDpZjH/SDyCitEKvwmQTyH+VaRwMX1gr1udWOz+sxEL2yt/2MyqBjO3aygDH9OtTK7jDqlPVtxkgYwNV1xoK9J01qtKOioqzTOfB9xE59LmE39avfJv/Q+jA7Gn9Jf5HXyYS0RQCovQ8jklcICBk3Xdx38Myut9W+nA="
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
    - secure: "D/D8RYjSyjMyP1pUvDc7NhHHRwuzTnxAFJ0z1RHluZ6WmILXtk+yOA8ZTUhAce6fSDvvyHnPl5z5+SVI+g7+qf7dR1wVpbL4qArvtZknVm9emJ3/TrZqqzhKpBjtYbI+VuI/2l27dlr/dsIVGvb3tvoHF9ZfG+uffxsbvgtoBgPOZuShtKqOKzmauUxXIiJD8GKttkpZ2Fa8/z2yLMxI3GA1nG7I4DKQjoiFy7HsPP7o3AiVN2ucnu0WxRWKjhoPdEI5duu6jYA61nn4t2k2hPwG3lndXqu4FjWRVh+l4pxd53KabDJC/2U9pXfqg5HDlyhW91n1V8SsMC6EVBv1bH7vRERjBSI656vnnP7j8Stat6Nu+6anR3wEuF9kR7jUn0n1qmmyvyO2qExJoZdBpVNVyYcywZw8Ltb7pSuhniCGLnt3pefS18s0/iATkJjaZMcp1CQ4rYMv38w0Qa8xjruVdpAbTXn/SSdm6FJsHGf6jbIrQfXNrOOg2HIHPjaOStYZ9RK5vR7uY/yqtj9W3oK5lqopZpjwypXuakACRy02WRzHye/cSZ3H8r+HDy2hK+kGLGD2lKIgG90n3qmkHYhfGq4c86LfW3E7KDFYtLCaEKFRg5/sejZ3LqX2RNFMT2dU7H5C0sE+N5BdDaEx8V13r9++n2K/EM0Agx2luBQ="
    # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "Ztf4Id9mav2T8ZP5Awo3OzoHgiIA1BoUnFeTAnyeDHZw2D/oiWitN7b5PnGfcC8gtfsbpyHrKZlw0sdimRlzFLTcLbyCKq6nwNgeK71eNkP1EUUzx9Lm7oOxfk2iDXi9OeA0s2hNu6N6ZGvjGAEZ0rgXc6b1qJsCcj+cG0EHACjrNqlB09c2L/nmihdmD1Eth7OGEnfq7pNr6ypRI/MnF/VI9TjguB0unIITi5NXQPBbaWKXlQ4OMgLNxecShtpmByzKFy+VQe+B0S+BxsyJyN2NTIDTE/J6KQ+u6GpRIWbw8BRcYQISieS3DnlpC6ES6Af3iAGkm+Cu+eD/Hxqj9tp5zMTuPDu/RuSuynYRvzRlr2ajcUBb3sRdsCTT+9CMJwf8BOOya5pfrdqkNoa/eSBdrt2lFGcxCCkM2nMXqJYCwNXxozpn4D6AVuSLy/s1AmHqg3nsGOcarID8VeHl8kzfK2rgInwTdQy/on6hueE+jvWpqlj8VqmsMK+I7zmJvzeOjuqZi/v5yk7mKeMNL0e4iy9sJq8Jwj+Jg5JVyT7IG2y5mU3moW2IhBpubSSRf/VSd3pv6RTVjF6su1gLcJdFmSiYQUyXAWg+zE1wbYrJCnhLz4ge3Ey8acJuTynjfVbdHPwhkeuzKy0IUxoxJ3jByglEA7PfvyopOknR6+U="
    # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "Fhf6lCKHDGYKfByvInvNoykitE9MRgTOmGKnfKpFIbUC4D3INkQLFZiE2zqsxkCNhVOiRHbWe5RlfJznd6z8Xbg91Ti+kLro18d9ys6Kh1ftOao+5LO5ndpzXkyORtqZ6y0AYqQ/YWn7sV1Zeev2psA3d7+A9+dh0Lbj36I1/gy03PrQ48TnhekP5u6hNXPK0gNMbSgLUIHBQM0n/zjbM8KNTmBvy8TsnyLrDaTuNsfmM5O5PrYweuirTX2ac7WDAiz3BkvA6ePgMBM4qIXlljJLIUBKjwSQQ4NqVrKvGq/+ONoaSLoAQqVh47h9JO3NvOr1HTPa0OVFFSOSPzbw/Jf/K43zC+MRJESGD8LMNO2V4ZKL6gPUEu0hQV24xrOf6iBDO1KuK3fhLeMf5+SsvQklLcKytU+WN8VLo01sWyfV7GFcNEIZKRvcNZCqhquBdPBQw96Y0aYdeiEgtwYdKkVs2gAiiIalbgDNcKE9cbcjbK1+u8cYDfqGqTXTlIluAwkVFJQcgKmXnDFgdaGJm/sPVCMgRLKqstN6V/3MAL+mb0VPz6Q41N2hJ9P3jqhGcqpXXwXog2pl1BxGbwafUM+ByRUcCX5MocGDMNTgmIS9lOaUzi44fBpLl8e47mEdcPVGKuJHsiwB6rnB2MA+Z3aWeLsF29YeRa08ScUFDFg="
