sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

after_success:
  - mvn jacoco:report coveralls:report

env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "gjGujK7IPO2oEUzMfs9lV67K2Nxv0aQ9/MZyvZ8OJXq8bw0BDKj2cBZFy8ENqHte5E53RctjN9C81JvBfZl9PLjQwX7UBVh7N8ZM5JvcchYcfBEbDh/QFhv7bXNr2vM7rqq71uOM+z/SYj91GwKg0zDcnT8Ggpon/Voozk3Jm+bAkDuCv+8wa2pNZPOnshJTAeEdMAcwppC9F+Aye8mGlq/qBsScUrrH1ducYbzlbDoVlPKZd/GlkzMKV5zSwYyrJ/jSRK7r2lDZnOV9i/1woESodGkTCJoaqyj5OaCpAp7qizKCOcsz8/jr2hCPaJ7U2tbSoRI7nugfnRpyUXts9qbCnEwrBphMaa2kLSfl5fqW7798ihTzGS57Pi9L/nELCpsy61Ty72F8j6ZgTep5nDLnC4GLRF7P06jfXkaGM5MtpTy0sTYC0lBpaCbEHVU3sNYwDM5Gj/ue0GAh9NHYpD3e5sDOt+Cn6YJsHJY4Gv5sGGPzNc4DPwgQQUVgXEYk316h9ga9GouJUUqS0GLI+qOJio9AmNWa/qWBo39R9Rsm8CRpTnBmA6bvas/QVRg9UG2eizCud2arZjCVPyKKirUhPBZTuKRTMNmEw6eIFjlnFPzbj+KoOjtmOuIcKFut6yrjOMfreMQLN3RDKDLQkWMVlOlad/Skl1W7FBChwfM="
    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
    - secure: "Z9iURpi/sOh/x2ezZKOtvgGnd4kHveROAzUYY+y8q76ukKq3RlC+bdJC0a3fGjdg85qm4fDrDaY8WAWBSmeK7+9qrqTJJKPQCT2zOO0bnKKH79Ik6raMKsC+tKl0i3PGke7fhTk4nJuQFeyJt4it32DBgT95wN6VCXUoG7SA9i6aFZyEvaCxrWHDHsfD6rNUy25CBjQQSABOp868BLuyz7JF2j05A/618UqFJj4ehHPTSnDhoEFGotWFuMRiyrCgu/wvL6UQGkqKGaxGmdik4QO/MPiywSPHdPGjzoH0Oorkouu0NAtw0I0T7Q8i93/I1QBLQwy2mY/nhjXwIX+uQe3MYRJCEkwLz1g6Dim4SHkD9exS5ZZBew/g+IRymKfrbNL5Ieu+VFQw9zSdflUJQSJltz4nWkQr8PEQHy1gXQ2mwBXzRxWfWNzKpQXPTm9tXB+CyVYRs0Ldk5FoLV+P13i61NDp8eOOnAmfikEcRv3p1GVQh2Mzo0gjhxFl3/74bxsJLHobZDpZjH/SDyCitEKvwmQTyH+VaRwMX1gr1udWOz+sxEL2yt/2MyqBjO3aygDH9OtTK7jDqlPVtxkgYwNV1xoK9J01qtKOioqzTOfB9xE59LmE39avfJv/Q+jA7Gn9Jf5HXyYS0RQCovQ8jklcICBk3Xdx38Myut9W+nA="
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
    - secure: "D/D8RYjSyjMyP1pUvDc7NhHHRwuzTnxAFJ0z1RHluZ6WmILXtk+yOA8ZTUhAce6fSDvvyHnPl5z5+SVI+g7+qf7dR1wVpbL4qArvtZknVm9emJ3/TrZqqzhKpBjtYbI+VuI/2l27dlr/dsIVGvb3tvoHF9ZfG+uffxsbvgtoBgPOZuShtKqOKzmauUxXIiJD8GKttkpZ2Fa8/z2yLMxI3GA1nG7I4DKQjoiFy7HsPP7o3AiVN2ucnu0WxRWKjhoPdEI5duu6jYA61nn4t2k2hPwG3lndXqu4FjWRVh+l4pxd53KabDJC/2U9pXfqg5HDlyhW91n1V8SsMC6EVBv1bH7vRERjBSI656vnnP7j8Stat6Nu+6anR3wEuF9kR7jUn0n1qmmyvyO2qExJoZdBpVNVyYcywZw8Ltb7pSuhniCGLnt3pefS18s0/iATkJjaZMcp1CQ4rYMv38w0Qa8xjruVdpAbTXn/SSdm6FJsHGf6jbIrQfXNrOOg2HIHPjaOStYZ9RK5vR7uY/yqtj9W3oK5lqopZpjwypXuakACRy02WRzHye/cSZ3H8r+HDy2hK+kGLGD2lKIgG90n3qmkHYhfGq4c86LfW3E7KDFYtLCaEKFRg5/sejZ3LqX2RNFMT2dU7H5C0sE+N5BdDaEx8V13r9++n2K/EM0Agx2luBQ="
    # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "Vx2js0x9Q7X9/9eiYxpHGqDom5YQmL9iXHJau9U7iUQcoZj2g7JPxZTeZ1+l4C6bwHTmHwuZ5qeLTKzufvzpbfEggQakX6jXZ4tWipqwlmrOtt97aAZQQiwD0P3phEkI80f2rLFwMrx9IuAb3Lk4/MpLO67h6bjkj+kaCDze8shgDELtSmoWeLSgezo+CV3caeLgy7RmFdEaoBErI4OEZonQEnoMAEe5TtLWWnSaM0J84j3kof2tiOJx/WwpXwDgp2LMB7ihYqIp+G6A9adNsKgLat1kmr9oVPuTogAkPNjh25Abr73WZlHkiuFVIhsyGTS5z8WyCBpsj67803V5gXFsnQiQrPEW8gqlJp9a/Qg6BDF9Lx7wVKDd5Rsg2rtvihWFslzgirxaO3D21MBZaLyRZMU95Fu7z1bh5CWu1RVA/WYl1TKIhqZ/M0o8YM9CQvvmzwV51qb/+0IZ4FwB9yswnr06NT251c5eg5hulH91oWV0f8L+QHr0RubJ4e/E5jqTtJCgtdCtsx/2s9SQF6d8Y2Irlene48hYXCYFf4eStJvRNs1Ajfn1/3JjUcdjwcoxLvmXd5GLWnjoMcf4G8eaNZYlIbWslgpgy5SlYCFe6QNYNtKZn7rusedt2VVHwpPjvDLRoKySBmvDCv+pwDvaGuod7sZESM7QXRxTI9U="
    # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "cC7ESKmuy4gstlLso++5Ig6yi9xVX7oFbDP63m8DmxfNfwnDTebBpBi1mBb/FUNN8TzCqLVr04C6hwFs09MmVv4XcNXK+K2VqM/MRWYbTuBxCKu+pN9sDUbBDAUxUulWIh0QXHdsYiPf8v2ZKQ3j2EnGYjsFT5RPgIwBMhgNNM54aEf7m1VnEdHABzBFRKwiUsUpeHMajEplnuogcPvSxeOkPjl9+6s2NOGObAm/7c9mDrEX4bvBy9OaInVVDIBg60cJt6uLpkXgQGlkZp24dijGK2ZjGuduo4Toirm4N4XyV8NUSYqcQFotaFY9508VZN5PO3c7Gz/jlBOlGIbe3yBvVSjrYX5BZlm/E5RAjUrf6awHXOMc9+xc2zFz/UUbpVHYv65I6aKygjqBR30yixscZcKAHzwQYI0VWwWCn3RmJDfHYlYrZHuTCxxuafWhzDW3QPdrFr4iCvKRgYFFUvBaeSWCkn4zSHW+79N4eyY7Dh701SAAdyUH2yKoZ4b+6oj+iHfG+JDhb/7+Ai6lN3lc590ICWGvqMalidK4cm79qSE1E+QKBT8+y0Pd+4ggSXvdvHiflPVZUQDg/kp8TXhZK2XRhtCUgWSLxvJTYlOmggHLZBMQNvGnkQfmq9UtqABwHBLdvuqchde77f1UwBOKMSUaAI/G7tsyd09CCWg="
